# Generated by Django 5.1.1 on 2024-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Country_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('CodeForces_Handle', models.CharField(blank=True, max_length=200, null=True)),
                ('Toph_Handle', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
